### ISSUE TITLE
Add support for Amazon on demand 2FA

### ISSUE THREAD

**Issue by sdga92** [pwablito/2fa_automation#22]
Add support for the Amazon page that sends an on demand 2fa request to the user.

**Comment by pwablito** [comment]
Before, I just included a prompt in the UI that would inform the user that they should go check their email and follow the instructions there. Then, when they perform the action, the page reloads automatically in the background window. At that point, another message is sent to the UI, which then overwrites the `amazon_ui_div` contents with whatever is next. I would propose using this solution but with more clear wording.
